### PR TITLE
CXFXJC-47: XJC DefaultValue plugin uses JAXBElement that does not have a default constructor

### PR DESCRIPTION
**Pull request by reta**
Follow up on https://github.com/apache/cxf-xjc-utils/pull/129

### CODE REVIEW

**Comment by reta** [comment]
@marcelhdl please let me know if I could push the change into your pull request instead, thank you

**Comment by marcelhdl** [comment]
yeah for sure

**Comment by reta** [comment]
Closing in favor of consolidating commits in https://github.com/apache/cxf-xjc-utils/pull/129

**Comment by marcelhdl** [comment]
@reta do you already knwo when the two new versions are released?

**Pull request closed without merging**
